#!/bin/bash

export HUBOT_HIPCHAT_JID=17214_1297130@chat.hipchat.com
export HUBOT_HIPCHAT_PASSWORD=moovbot
export HUBOT_HIPCHAT_ROOMS=17214_mtg_room@conf.hipchat.com,17214_dd@conf.hipchat.com,17214_social@conf.hipchat.com
export HUBOT_LOG_LEVEL="debug"

bin/hubot --adapter hipchat
